language: node_js
node_js:
  - "6"

before_install:
  - npm install -g yarn

install:
  - yarn
  - cd client
  - yarn

before_script:
  - pwd
  - npm test
  - npm install -g strongloop --ignore-scripts

script:
  - pwd
  - npm run build
  - cd ..
  - slc build --npm

after_success:
  script:
    - pwd
    - echo $SSH_KEY_RAW > key
    - ls
    - slc --version
    - SSH_KEY=$PWD/key slc deploy -s main http+ssh://cs.ragg.fr:8701 ../Captain_standard-1.0.0.tgz
  on:
    branch: testprod

after_failure:
  script:
    - npm ls -g
    - ls -la
    - head -n1 key

