language: node_js
node_js:
  - "6"

before_install:
  - npm install -g yarn

install:
  - yarn
  - cd client
  - yarn

script:
  - npm test

before_deploy:
  - npm install -g strongloop --ignore-scripts
  - npm run build
  - cd ..
  - slc build --npm

deploy:
  provider: script
  skip_cleanup: true
  script: bash --login -c "source $HOME/.nvm/nvm.sh && nvm use $TRAVIS_NODE_VERSION && $TRAVIS_BUILD_DIR/deploy.sh"
  on:
    branch: production

after_failure:
  - npm ls -g
  - ls -la
  - head -n1 key

cache:
  directories:
  - $HOME/.yarn-cache

