language: node_js
node_js:
  - "6"

before_install:
  - npm install -g yarn

install:
  - yarn
  - cd client
  - yarn

before_script:
  - pwd
  - npm test
  - npm install -g strongloop --ignore-scripts

script:
  - pwd
  - npm run build
  - cd ..
  - slc build --npm

before_deploy:
  - pwd
  - echo $SSH_KEY_RAW > key

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: testprod
