language: node_js
node_js:
  - "6"

before_install:
  - npm install -g yarn

install:
  - yarn
  - cd client
  - yarn

before_script:
  - npm test
  - npm install -g strongloop --ignore-scripts

script:
  - npm run build
  - cd ..
  - slc build --npm

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: testprod

after_failure:
  - npm ls -g
  - ls -la
  - head -n1 key

