---
# time-related tasks

- name: install system packages for time management
  apt: name=ntp,tzdata state=latest update-cache=yes

- name: set timezone to {{ timezone }}
  template: src=etc/timezone dest=/etc/timezone
  notify: update-tzdata
