- name: install node repo
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: Install nodejs
  apt:
    name: nodejs
    update_cache: yes

- name: Install yarn
  npm: name=yarn global=yes

- name: install strongloop
  when: env != 'production'
  npm: name=strongloop global=yes

- name: install strong-pm
  when: env == 'production'
  npm: name=strong-pm global=yes

- name: install strong-pm service
  when: env == 'production'
  shell: sl-pm-install --systemd creates=/etc/systemd/system/strong-pm.service

- name: run strong-pm service
  when: env == 'production'
  shell: systemctl start strong-pm

- name: find service
  when: env == 'production'
  shell: slpmctl ls|grep " main "
  register: serviceFound
  ignore_errors: True

- name: create service
  when: env == 'production' and serviceFound|failed
  shell: slpmctl create main

- name: configure service size
  when: env == 'production'
  shell: slpmctl set-size main 1

- name: configure service env
  when: env == 'production'
  shell: slpmctl env-set main NODE_ENV=production PORT={{ app_port }}
