---
- hosts: all
  become: true
  vars:
    app_path: /app
    app_name: captain_standard
    app_port: 2000
    postgresql:
      user: default
      password: password
      database: password
  roles:
    - common
    - apache
    - nodejs
    - postgresql
