---
- hosts: all
  become: true
  gather_facts: no
  vars:
    app_path: /vagrant
    app_name: captain_standard
    app_port: 2000
    postgresql:
      user: default
      password: password
      database: password
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup:
  roles:
    - common
    - apache
    - nodejs
    - postgresql
