---
# PostgreSQL Installation

- name: install postgresql
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - postgresql
    - python-psycopg2
  tags: postgresql
  notify: restart-postgresql

- name: create postgresql user
  postgresql_user: name={{ postgresql.user }} password={{ postgresql.password }}
  become: true
  become_user: postgres
  tags: postgresql

- name: create postgresql database
  postgresql_db: name={{ postgresql.database }} encoding='UTF-8' template='template0' owner={{ postgresql.user }}
  become: true
  become_user: postgres
  tags: postgresql

- name: grant auth on psql database
  postgresql_privs: db={{ postgresql.database }} privs=ALL roles={{ postgresql.user }} type=database
  become: true
  become_user: postgres
  tags: postgresql

